version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379" # exposes Redis to your Windows host
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
